// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBook() {
  return window['go']['read']['App']['GetBook']();
}

export function GetBookshelf() {
  return window['go']['read']['App']['GetBookshelf']();
}

export function Lock() {
  return window['go']['read']['App']['Lock']();
}

export function ReloadPage(arg1) {
  return window['go']['read']['App']['ReloadPage'](arg1);
}

export function RemoveBook(arg1) {
  return window['go']['read']['App']['RemoveBook'](arg1);
}

export function SelectFile() {
  return window['go']['read']['App']['SelectFile']();
}

export function TryLock() {
  return window['go']['read']['App']['TryLock']();
}

export function Unlock() {
  return window['go']['read']['App']['Unlock']();
}
