// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitSetting() {
  return window['go']['setting']['App']['InitSetting']();
}

export function Lock() {
  return window['go']['setting']['App']['Lock']();
}

export function SaveSetting(arg1) {
  return window['go']['setting']['App']['SaveSetting'](arg1);
}

export function SetReadPanel(arg1, arg2) {
  return window['go']['setting']['App']['SetReadPanel'](arg1, arg2);
}

export function TryLock() {
  return window['go']['setting']['App']['TryLock']();
}

export function Unlock() {
  return window['go']['setting']['App']['Unlock']();
}
