// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function InitSetting():Promise<db.Setting>;

export function Lock():Promise<void>;

export function SaveSetting(arg1:db.Setting):Promise<boolean>;

export function SetReadPanel(arg1:number,arg2:number):Promise<boolean>;

export function TryLock():Promise<boolean>;

export function Unlock():Promise<void>;
